// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import CallUpCleanerController from "./call_up_cleaner_controller"
application.register("call-up-cleaner", CallUpCleanerController)

import TurboLoaderController from "./call_up_loader_controller"
application.register("call-up-loader", TurboLoaderController)

import CallUpSelectorController from "./call_up_selector_controller"
application.register("call-up-selector", CallUpSelectorController)

import CategoriesController from "./categories_controller"
application.register("categories", CategoriesController)

import CategoryRulesController from "./category_rules_controller"
application.register("category-rules", CategoryRulesController)

import ClickableRowController from "./clickable_row_controller"
application.register("clickable-row", ClickableRowController)

import EditToggleController from "./edit_toggle_controller"
application.register("edit-toggle", EditToggleController)

import ExternalPlayerController from "./external_player_controller"
application.register("external-player", ExternalPlayerController)

import FrameCloserController from "./frame_closer_controller"
application.register("frame-closer", FrameCloserController)

import HandlePreviewController from "./handle_preview_controller"
application.register("handle-preview", HandlePreviewController)

import HelloController from "./hello_controller"
application.register("hello", HelloController)

import ImagePreviewController from "./image_preview_controller"
application.register("image-preview", ImagePreviewController)

import LazyLoaderController from "./lazy_loader_controller"
application.register("lazy-loader", LazyLoaderController)

import MatchDetailsLoaderController from "./match_details_loader_controller"
application.register("match-details-loader", MatchDetailsLoaderController)

import MatchFormController from "./match_form_controller"
application.register("match-form", MatchFormController)

import ModalLoaderController from "./modal_loader_controller"
application.register("modal-loader", ModalLoaderController)

import RemoteModalController from "./remote_modal_controller"
application.register("remote-modal", RemoteModalController)

import SchoolCupController from "./school_cup_controller"
application.register("school-cup", SchoolCupController)

import SchoolTabController from "./school_tab_controller"
application.register("school-tab", SchoolTabController)

import SchoolTogglesController from "./school_toggles_controller"
application.register("school-toggles", SchoolTogglesController)

import TabRedirectController from "./tab_redirect_controller"
application.register("tab-redirect", TabRedirectController)
