// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import HandlePreviewController from "./handle_preview_controller"
application.register("handle-preview", HandlePreviewController)

import HelloController from "./hello_controller"
application.register("hello", HelloController)

import SchoolCupController from "./school_cup_controller"
application.register("school-cup", SchoolCupController)

import SchoolTogglesController from "./school_toggles_controller"
application.register("school-toggles", SchoolTogglesController)

import SchoolTabController from "./school_tab_controller"
application.register("school-tab", SchoolTabController)

import CategoriesController from "./categories_controller"
application.register("categories", CategoriesController)