default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>


development:
  <<: *default
  database: one_super_ten_development

test:
  <<: *default
  database: one_super_ten_test

production:
  primary: &primary_production
    <<: *default
    database: one_super_ten_production
    username: one_super_ten
    password: <%= ENV["ONE_SUPER_TEN_DATABASE_PASSWORD"] %>
  cache:
    <<: *primary_production
    database: one_super_ten_production_cache
    migrations_paths: db/cache_migrate
  queue:
    <<: *primary_production
    database: one_super_ten_production_queue
    migrations_paths: db/queue_migrate
  cable:
    <<: *primary_production
    database: one_super_ten_production_cable
    migrations_paths: db/cable_migrate
