default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

sqlite: &sqlite
  adapter: sqlite3
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000

development:
  primary:
    <<: *default
    database: one_super_ten_development
  cache:
    <<: *sqlite
    database: solid/one_super_ten_development_cache
    migrations_paths: db/cache_migrate

test:
  <<: *default
  database: one_super_ten_test

staging:
  primary:
    <<: *default
    url: <%= ENV["DATABASE_URL"] %>
  cache:
    <<: *default
    url: <%= ENV["DATABASE_URL"] %>
    migrations_paths: db/cache_migrate
  queue:
    <<: *default
    url: <%= ENV["DATABASE_URL"] %>
    migrations_paths: db/queue_migrate
  cable:
    <<: *default
    url: <%= ENV["DATABASE_URL"] %>
    migrations_paths: db/cable_migrate

# production:
#   primary: &primary_production
#     <<: *default
#     database: one_super_ten_production
#     username: one_super_ten
#     password: <%= ENV["ONE_SUPER_TEN_DATABASE_PASSWORD"] %>
#   cache:
#     <<: *primary_production
#     database: one_super_ten_production_cache
#     migrations_paths: db/cache_migrate
#   queue:
#     <<: *primary_production
#     database: one_super_ten_production_queue
#     migrations_paths: db/queue_migrate
#   cable:
#     <<: *primary_production
#     database: one_super_ten_production_cable
#     migrations_paths: db/cable_migrate
