test:
  service: Disk
  root: <%= Rails.root.join("tmp/storage") %>

local:
  service: Disk
  root: <%= Rails.root.join("storage") %>

r2_public:
  service: S3
  access_key_id: <%= Rails.application.credentials.dig(:r2, :access_key_id) %>
  secret_access_key: <%= Rails.application.credentials.dig(:r2, :secret_access_key) %>
  region: us-east-1
  bucket: tenant-public-assets
  endpoint: https://b5988d898f725f.r2.dev
  force_path_style: true
  ssl_verify_peer: true
  http_continue_timeout: 1

r2_private:
  service: S3
  access_key_id: <%= Rails.application.credentials.dig(:r2, :access_key_id) %>
  secret_access_key: <%= Rails.application.credentials.dig(:r2, :secret_access_key) %>
  region: us-east-1
  bucket: tenant-private-assets
  endpoint: https://b5988d898f725f.r2.cloudflarestorage.com
  force_path_style: true
  ssl_verify_peer: true
  http_continue_timeout: 1
