test:
  service: Disk
  root: <%= Rails.root.join("tmp/storage") %>

local:
  service: Disk
  root: <%= Rails.root.join("storage") %>

r2_public:
  service: CustomR2Public
  access_key_id: <%= Rails.application.credentials.dig(:r2, :access_key_id) %>
  secret_access_key: <%= Rails.application.credentials.dig(:r2, :secret_access_key) %>
  region: us-east-1
  bucket: tenant-public-assets
  endpoint: https://5b92308a38293a7585595315c458b8e7.r2.cloudflarestorage.com
  force_path_style: true
  ssl_verify_peer: false

r2_private:
  service: CustomR2Private
  access_key_id: <%= Rails.application.credentials.dig(:r2, :access_key_id) %>
  secret_access_key: <%= Rails.application.credentials.dig(:r2, :secret_access_key) %>
  region: us-east-1
  bucket: tenant-private-assets
  endpoint: https://5b92308a38293a7585595315c458b8e7.r2.cloudflarestorage.com
  force_path_style: true
  ssl_verify_peer: true
